name: CI Pipeline for Shailun App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Linting
      - name: Run Flake8 Lint
        run: flake8 .

      # 5️⃣ Bandit Security Scan
      - name: Bandit Scan
        run: bandit -r .

      # 6️⃣ Unit Tests + Coverage
      - name: Run Unit Tests with Coverage
        run: pytest --cov=shailuns --cov-fail-under=80

      # 7️⃣ Build Docker Image
      - name: Build Docker Image
        run: docker build -t shailun-app:latest .

      # 8️⃣ Docker Image Scan
      - name: Trivy Docker Image Scan
        run: trivy image --exit-code 0 --severity CRITICAL,HIGH shailun-app:latest

      # 9️⃣ Push Docker Image
      - name: Push Docker Image
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker tag shailun-app:latest ${{ secrets.DOCKER_USER }}/shailun-app:latest
          docker push ${{ secrets.DOCKER_USER }}/shailun-app:latest

