name: CI Pipeline for Shailun App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Linting
      - name: Run Flake8 Lint
        run: |
          pip install flake8
          flake8 . || true   # ignore errors for now

      # 5️⃣ Bandit Security Scan
      - name: Bandit Scan
        run: |
          pip install bandit
          bandit -r . || true   # ignore errors for now

      # 6️⃣ Trivy File System Scan
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'

      # 7️⃣ Unit Tests + Coverage
      - name: Run Unit Tests with Coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=shailuns --cov-fail-under=80 || true

      # 8️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t shailun-app:latest .

      # 9️⃣ Docker Image Scan
      - name: Trivy Docker Image Scan
        run: |
          trivy image --exit-code 0 --severity CRITICAL,HIGH shailun-app:latest

      # 🔟 Push Docker Image to Docker Hub (Optional)
      - name: Push Docker Image
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker tag shailun-app:latest ${{ secrets.DOCKER_USER }}/shailun-app:latest
          docker push ${{ secrets.DOCKER_USER }}/shailun-app:latest
