name: Basic CI Pipeline for Shailun App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Lint the code
      - name: Run Flake8 Lint
        run: |
          pip install flake8
          flake8 .

      # 5️⃣ Security scan with Bandit
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r .

      # 6️⃣ Trivy File System Scan
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'

